# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    toolchain:
        docker:
          - image: fedora:latest
        working_directory: /root/animedb
        steps:
          - checkout
          - restore_cache:
              keys:
                - toolchain-{{ .Revision }}
          - run:
              name: toolchain download
              command: |
                cd /root/animedb/animedb/scripts
                sh toolchain.sh
          - save_cache:
              key: toolchain-{{ .Revision }}
              paths:
                - /root/animedb/animedb/compiler
                - /root/animedb/animedb/make
    build-test:
      docker:
        - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
      working_directory: /root/animedb
      steps:
        - checkout
        - restore_cache:
            keys:
              - toolchain-{{ .Revision }}
        - run:
            name: run build
            command: |
              cd /root/animedb/animedb/scripts
              make TARGET=linux testlib -j4
        - save_cache:
            key: binary-test-{{ .Revision }}
            paths:
              - /root/animedb/animedb/binary
    test:
      docker:
        - image: fedora:latest
      working_directory: /root/animedb
      steps:
        - restore_cache:
            keys:
              - binary-test-{{ .Revision }}
        - run: 
            name: run tests
            command: |
              cd /root/animedb/animedb/binary
              ./test
              mkdir test-results && mkdir test-results/cute-cpp
              mv test.xml ./test-results/cute-cpp/
        - store_test_results:
            path: /root/animedb/animedb/binary/test-results
        - store_artifacts:
            path: /root/animedb/animedb/binary/test-results
            destination: animedb-test-results
    build:
      docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
      working_directory: /root/animedb
      steps:
        - checkout
        - restore_cache:
            keys:
              - toolchain-{{ .Revision }}
        - run:
            name: run build
            command: |
              cd /root/animedb/animedb
              export PATH=/root/animedb/animedb/compiler/msdk-4.3.6-mips-EL-2.6.34-0.9.30.3_hwfpu/bin:$PATH
              make TARGET=mipsel all -j4
              make TARGET=mipsel tarball
        - store_artifacts:
            path: /root/animedb/animedb/binary
            destination: animedb-{{ .BuildNum }}-binary
        - store_artifacts:
            path: /root/animedb/animedb/animedb.tar.gz
            destination: animedb-{{ .BuildNum }}-tar-gz
workflows:
  version: 2
  build_and_test:
    jobs:
      - toolchain
      - build-test:
          requires:
            - toolchain
      - test:
          requires:
            - build-test
      - build:
          requires:
            - test
