# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/animedb

    steps:
      - checkout
      - restore_cache:
          keys:
            - toolchain
      - run: 
            cd ~/animedb/animedb/scripts && sh toolchain.sh
      - save_cache:
          key: toolchain
          paths:
            - ./compiler
            - ./make
      - run: cd ~/animedb/animedb/scripts && sh ci_run.sh
      # run tests!
      - run: ./binary/test


