# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  toolchain:
      docker:
        - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
      working_directory: /root/animedb
      steps:
        - checkout
        - restore_cache:
            keys:
              - toolchain
        - run:
            name: toolchain download
            command: |
              cd ./animedb/scripts
              sh toolchain.sh
        - save_cache:
            key: toolchain
            paths:
              - ./animedb/compiler
      build:
        docker:
          - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
        working_directory: /root/animedb
        steps:
          - checkout
          - restore_cache:
              keys:
                - toolchain
          - run:
              name: run build
              command: |
                cd ./animedb/scripts
                sh ci_run.sh
          - save_cache:
              key: binary
              paths:
                - ./animedb/compiler
      test:
        docker:
          - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
        working_directory: /root/animedb
        steps:
          - restore_cache:
              keys:
                - binary
          - run: 
              name: run tests
              command: |
                cd ./animedb/scripts
                ./test

workflows:
  version: 2
  build_and_test:
    jobs:
      - toolchain
      - build:
          requires:
            - toolchain
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
