# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    toolchain:
        docker:
          - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
        working_directory: /root/animedb
        steps:
          - checkout
          - restore_cache:
              keys:
                - toolchain-{{ .Revision }}
          - run:
              name: toolchain download
              command: |
                cd /root/animedb/animedb/scripts
                sh toolchain.sh
          - save_cache:
              key: toolchain-{{ .Revision }}
              paths:
                - /root/animedb/animedb/compiler
                - /root/animedb/animedb/make
    build:
      docker:
        - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
      working_directory: /root/animedb
      steps:
        - checkout
        - restore_cache:
            keys:
              - toolchain-{{ .Revision }}
        - run:
            name: run build
            command: |
              cd /root/animedb/animedb/scripts
              sh ci_run.sh
        - save_cache:
            key: binary-{{ .Revision }}
            paths:
              - /root/animedb/animedb/binary
    test:
      docker:
        - image: circleci/build-image:ubuntu-14.04-enterprise-945-8fcbc5a
      working_directory: /root/animedb
      steps:
        - restore_cache:
            keys:
              - binary-{{ .Revision }}
        - run: 
            name: run tests
            command: |
              cd /root/animedb/animedb/binary
              ./test
workflows:
  version: 2
  build_and_test:
    jobs:
      - toolchain
      - build:
          requires:
            - toolchain
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
