# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  toolchain:
      docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
      working_directory: ~/animedb/animedb/scripts
      steps:
        - checkout
        - restore_cache:
            keys:
              - toolchain
        - run:
            name: toolchain download
            command: sh toolchain.sh
        - save_cache:
            key: toolchain
            paths:
              - ./compiler
        - run: cd ~/animedb/animedb/scripts && sh ci_run.sh
      build:
        docker:
          - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
        working_directory: ~/animedb/animedb/scripts
        steps:
          - checkout
          - restore_cache:
              keys:
                - toolchain
          - run:
              name: run build
              command: sh ci_run.sh
          - save_cache:
              key: binary
              paths:
                - ./../compiler
      test:
        docker:
          - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
        working_directory: ~/animedb/animedb/binary
        steps:
          - restore_cache:
              keys:
                - binary
          - run: 
              name: run tests
              command: ./test

workflows:
  version: 2
  build_and_test:
    jobs:
      - toolchain
      - build
          requires:
            - toolchain
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
