

BINARY_NAME = $(addsuffix $(TARGET),animedb_) 

ifeq ($(TARGET),testlib)
BINARY_NAME = $(addsuffix $(TARGET).a,animedb_) 
endif

STRIP = strip
CXX = g++
CC = gcc

LDFLAGS = -L./lib/linux
CXXFLAGS = -D_DEBUG
STRIP = echo

obj/linux/%.o: src/%.cpp
			$(CXX) $(CXXFLAGS) $(CXXINCLUDES) src/$*.cpp -o $@

obj/linux/%.o: app/%.cpp
			$(CXX) $(CXXFLAGS) $(CXXINCLUDES) -I./src app/$*.cpp -o $@


include Makefile.common
